### PR TITLE
Update for Rack2

### PR DESCRIPTION
**Pull request by SteveRussell33**

### CODE REVIEW

**Comment by jhoar** [comment]
Hi Steve,

Thanks for the PR.  I have been completely disconnected from Rack for the past few years but since V2 seems to be round the corner I'll see if I can rebuild the long long development environment and get everything working again...

**Comment by SteveRussell33** [comment]
Hi John,

Thanks for getting in touch. No problem, glad to help! 
I've seen that Dave has reached out to you as he's been working on your other repo. Anything you can do to assist would be greatly appreciated by the community.
Quick question: I noticed that the "refactor" branch has an unreleased filter module, I was testing it last night and was getting some good results - can't have too many filters right?! ;)
Would you say that the code, as it is presently, is finished? If so I was thinking of merging this branch with the master on my fork to release to the VCV Rack2 library when that goes live. Thoughts?

All the best
Steve

**Comment by jhoar** [comment]
Hi,

I was going back through the code and there are a couple of things that need to be completed for the new filter module (which is the filter from the main module). So I was going to merge in your PR with the last changes and merge everything back to master for release.

**Comment by jhoar** [comment]
Dear Steve,

I hope this message find you well. 

Over the past couple of weeks I have tried to find time to work on Rack, but I have realised that I neither have time nor energy for it. So I come back to your original idea of releasing it for Rack2 from your repo. If you are still interested, you are certainly welcome to do so. 

cheers,

john

**Comment by SteveRussell33** [comment]
Hi John,

That's OK, I understand that not everyone has the time needed to maintain a project. 

I shall contact Christoph https://community.vcvrack.com/u/cschol by PM (who is the maintainer of the Rack library) on the community forum and pass your message on, so that he can see that you have transferred the maintenance of these modules over to me. I'll keep this issue open for the time being just in case Andrew/VCV Support needs to see it/add to it.

What I'll do is rename the ```refactor``` branch on my fork as ```Rack2``` and submit that as the URL to the library. Any issues/ideas people may have can go there.

Thank you for doing the original port, I know a few people will be pleased to see this make it over to Rack2.
Hope you are well and wish you all the best for the future.

Cheers
Steve

**Comment by cschol** [comment]
@jhoar Thank you also for your original port of the SMR functionality.

I use it extensively and I am glad that @SteveRussell33 is picking it up. 

@SteveRussell33 Update the original issue in the Library when you are ready and I will confirm that ownership transfer is completed.

**Comment by SteveRussell33** [comment]
Updated Library issue; closing.

**Pull request closed without merging**
